version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    labels: ["no changelog", "merge when ready", "dependencies", "github_actions"]
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: /
    labels: ["no changelog", "merge when ready", "dependencies", "javascript"]
    schedule:
      interval: monthly
