{{- if and .Values.ingress.enabled .Values.ingress.tls.enabled (not .Values.ingress.tls.existingSecret) }}
{{- if and .Values.ingress.tls.certificate .Values.ingress.tls.privateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "policy-bot.tlsSecretName" . }}
  labels:
    {{- include "policy-bot.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.ingress.tls.certificate }}
  tls.key: {{ .Values.ingress.tls.privateKey }}
{{- end }}
{{- end }}
