plugins:
  resolvers:
    - https://palantir.bintray.com/releases/{{GroupPath}}/{{Product}}/{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: "com.palantir.godel-mod-plugin:mod-plugin:1.0.1"
        checksums:
          darwin-amd64: df22922bacfe4e4e7c255607a0aace176205f04ae001f3746276fcfab1780e01
          linux-amd64: a2697b3d504bb37c2fd8831a66c7014927a6d94e4dfb9765b4764354370a1ab6

environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"

exclude:
  names:
  - \..+
  - vendor
  paths:
  - godel
