# This policy allows the `palantir/catskills` team to approve anything,
# and the `palantir/devtools` team can approve changes to staging.

policy:
  approval:
  - or:
    - catskills
    - devtools

approval_rules:

- name: catskills
  description: catskills can approve
  requires:
    count: 1
    teams: ["palantir/catskills"]

- name: devtools
  description: devtools can approve changes to staging
  if:
    only_changed_files:
      paths:
      - '^staging\.palantir\.com/.*'
  requires:
    count: 1
    teams: ["palantir/devtools"]
