# This policy requires an approval from a member on a specific team,
# in this case, `palantir/devtools`. It also allows disapprovals from
# anyone in the `palantir` organization.

policy:
  approval:
  - the devtools team has approved

  disapproval:
    requires:
      organization:
      - "palantir"

approval_rules:
- name: the devtools team has approved
  requires:
    count: 1
    teams:
    - "palantir/devtools"
